#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/cm15acr/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/cm15acr/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/cm15acr/OB-Temporal-Filtering/Temporal-Filtering/Single-Cells/MCs/Channels/x86_64/.libs/libnrnmech.so" "$@"
