#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/christophe/nrn-7.4"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/christophe/nrn-7.4/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/christophe/OB-MC-PGC/Temporal-Filtering/Networks/Basic-MC-PGC-Motif/Class/Channels/x86_64/.libs/libnrnmech.so" "$@"
